os: Visual Studio 2015

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: kpipes-desktop
  matrix:
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build: false

test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% --package kpipes-desktop &&
      cargo build --target %TARGET% --package kpipes-desktop --release &&
      cargo test --target %TARGET% --package kpipes-core &&
      cargo test --target %TARGET% --package kpipes-desktop &&
      cargo test --target %TARGET% --package kpipes-core --release &&
      cargo test --target %TARGET% --package kpipes-desktop --release
    )

before_deploy:
  - cargo rustc --target %TARGET% --package %CRATE_NAME% --release --bin %CRATE_NAME%
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: RwkTztCb5QNbfu4DvEY5siwtLTBafjv9ivoKpa1eSgXwr/h4KFZYmhPR5mgyY6he
  description: ''
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
    - kpipes-qt

notifications:
  - provider: Email
    on_build_success: false
