[package]
name = "kpipes"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = "^1.2.0"
cgmath = "^0.17.0"
futures = "^0.3.5"
lazy_static = "^1.4.0"
winit = "^0.22.2"
wgpu = "^0.5.2"
