[package]
name = "kpipes-desktop"
version = "1.0.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[dependencies]
kpipes-core = { version = "1.0.0", path = "../kpipes-core" }
env_logger = "^0.7.1"
futures = "^0.3.5"
log = "^0.4.11"
winit = "^0.22.2"
wgpu = "^0.5.2"
