[package]
name = "kpipes-qt-rust"
version = "0.1.0"
authors = ["Kneelawk <kneelawk@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
kpipes-core = { version = "1.0.1", path = "../../kpipes-core" }

[build-dependencies]
cbindgen = "^0.14.3"
